### ISSUE TITLE
Manually Installing without Pod

### ISSUE THREAD

**Issue by Sun3** [sxg/ForecastIO#19]
Are there instructions on how to install all of the dependencies without using Pods?

I am getting error:

`
Library not loaded: @rpath/ForecastIO.framework/ForecastIO
`

Thanks.

**Comment by sxg** [comment]
How are you currently adding ForecastIO to your project? It should work fine by just dragging and dropping the ForecastIO project into whatever project you're working on.

**Comment by Sun3** [comment]
I copied the Source folder into my project. Then I was going to add any dependencies manually.

**Comment by sxg** [comment]
Go to your app target > Build Phases. Add the ForecastIO framework as a target dependency. There's a different framework for watchOS, iOS, tvOS, and OS X - just add whichever ones you need. Take a look at the included iOS example project too. Let me know if that works - I'll add more details in the README soon!
<img width="1495" alt="screen shot 2016-07-16 at 6 08 14 pm" src="https://cloud.githubusercontent.com/assets/3487285/16897458/4f056650-4b80-11e6-94e0-6c56722cc585.png">

**Comment by Sun3** [comment]
Thanks, its working. Great job on the framework.
