### ISSUE TITLE
Get extended hourly forecast

### ISSUE THREAD

**Issue by alexkotenko** [sxg/ForecastIO#20]
How could I get extended hourly forecast (by using extend=hourly option on get-request) for the next seven days using this library?
Basically, it's not only about extended hourly forecast. There is a lot of request options described in API docs (and "extend=hourly" just one of them), so could it be used with this library?

**Comment by sxg** [comment]
There's an optional parameter on the `getForecast` method for the `extendHourly` option. A couple other optional parameters also exist, and they should be detailed in the docs. I'll add some detail on these optional parameters in the README, and I'll try to add support for more that are described in the Dark Sky API docs.

**Comment by alexkotenko** [comment]
Thank you for your reply. It turned out that I had old version of library (1.6.1) so I couldn't find any mention of hourly options.
