### ISSUE TITLE
"open" keyword generates compiler errors (Swift 3.0)

### ISSUE THREAD

**Issue by PGO11** [sxg/ForecastIO#27]
/// A class to interact with the Dark Sky API.
open class APIClient : NSObject {

APIClient.swift:12:1: Expressions are not allowed at the top level
APIClient.swift:12:5: Consecutive statements on a line must be separated by ';'
APIClient.swift:12:1: Ambiguous use of 'open'

I was able to compile replacing the instances of "open" with "public".

(Xcode 8 beta 5, iOS 10, Swift 3)

**Comment by sxg** [comment]
Hey, so the open keyword is new to Xcode 8 beta 6 (released on Monday).
Things should work if you update. Let me know!

**Comment by PGO11** [comment]
Snap, they don't call it the bleeding edge not for nothin', thanks!

(Can't update right now tho, but I assume it'll work.)
