### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by kwstasna** [sxg/ForecastIO#28]
Hello.
Very nice library first of all!

Is there any way to learn the weather for a certain date? Because i have lat and lon but i just want to change the date and not to see what the weather is now!
Thanks a lot :D

**Comment by sxg** [comment]
Hey, thanks! What you want is [this API](
http://cocoadocs.org/docsets/ForecastIO/2.1.1/Classes/APIClient.html#/s:FC10ForecastIO9APIClient11getForecastFT8latitudeSd9longitudeSd4timeCSo6NSDate21excludeForecastFieldsGSaOS_13ForecastField_10completionFT8forecastGSqVS_8Forecast_5errorGSqCSo7NSError__T__T_).
It'll let you specify a time (past or future) for your weather data.

**Comment by sxg** [comment]
Hey, thanks! What you want is [this API](http://cocoadocs.org/docsets/ForecastIO/2.1.1/Classes/APIClient.html#/s:FC10ForecastIO9APIClient11getForecastFT8latitudeSd9longitudeSd4timeCSo6NSDate21excludeForecastFieldsGSaOS_13ForecastField_10completionFT8forecastGSqVS_8Forecast_5errorGSqCSo7NSError__T__T_). It'll let you specify a time (past or future) for your weather data.
