### ISSUE TITLE
Forecast.io is now DarkSky.net

### ISSUE THREAD

**Issue by caipre** [sxg/ForecastIO#30]
Copied from an email to forecast.io registered accounts:

> First, we’re consolidating our branding under the Dark Sky name, getting rid of Forecast.io entirely. We’ve found that people often don’t realize the two are related, and this causes a lot of confusion.
> 
> This means a few things for you as a developer:
> -  The developer portal is now https://darksky.net/dev/.
> - The attribution requirement of the Terms of Service have changed. Attribution should:
>   - Display “Powered by Dark Sky”
>   - Link to https://darksky.net/poweredby/.
>   - Please make this change at your earliest convenience!
> - The API endpoint has changed from https://api.forecast.io/ to https://api.darksky.net/.

**Comment by sxg** [comment]
Thanks for the heads up! It looks like the old API endpoint still works, so I'm going to wait and push out a major version update sometime this weekend including the new API endpoint. As far as names go, this project will still be called ForecastIO (unless there are serious objections).

**Comment by sxg** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tsvD1lB5&#x2F;7-update-api-endpoint"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update API endpoint</a>
