### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by HassanSE** [sxg/ForecastIO#46]
Hello,

I'm getting following error as I installed ForecastIO pod:

> /---/---/ForecastViewController.swift:10:8: Module file was created by an older version of the compiler; rebuild 'ForecastIO' and try again: /---/---/Library/Developer/Xcode/DerivedData/SwiftyWeather-fcvyupiaiunpivcfwaqvzlakstdf/Build/Products/Debug-iphonesimulator/ForecastIO.framework/Modules/ForecastIO.swiftmodule/x86_64.swiftmodule

Any clue?

**Comment by sxg** [comment]
What version of Xcode are you using? What's the output of `xcodebuild -version`? Try cleaning your project and deleting the DerivedData folder.

**Comment by HassanSE** [comment]
Deleting DerivedData folder worked. Thanks.
