### ISSUE TITLE
Forecast.swift: Unable to bridge NSNumber to Float.

### ISSUE THREAD

**Issue by swiftdesginer0** [sxg/ForecastIO#49]
When the public init(fromJSON json: NSDictionary) (line 68) is called and it attempts to bridge the type NSNumber to Float, it causes a fatal error. I am running it with Swift 4 with iOS 11.3 and Xcode beta 9.3. Has anybody heard of this issue?

**Comment by joeljfischer** [comment]
I'm getting it on Xcode 9.3 final. It's an easy fix, change Floats to Doubles.

**Comment by joeljfischer** [comment]
See #50

**Comment by sxg** [comment]
This is fixed in the 4.1.0 release thanks to @joeljfischer and #50. Thanks!
