### ISSUE TITLE
Unable to bridge NSNumber to Float Swift 3.3

### ISSUE THREAD

**Issue by V1ki** [sxg/ForecastIO#51]
In Swift 3.3 .  
sometime got error ,because Unable to bridge NSNumber to Float Swift 3.3.

latitude = json["latitude"] as! Float

you should fix like [this](https://stackoverflow.com/questions/49641887/unable-to-bridge-nsnumber-to-float-swift-3-3)

**Comment by sxg** [comment]
This should be fixed in the latest release of ForecastIO (5.0.0). Are you able to update to that? See #49 and #50.

**Comment by V1ki** [comment]
o(╯□╰)o
