### ISSUE TITLE
Unexpected Error on all Forecast requests

### ISSUE THREAD

**Issue by Vortec4800** [sxg/ForecastIO#61]
This started yesterday. Has anyone else started seeing this? It seems like perhaps there was an API change or something? I'll keep investigating in the meantime.

**Comment by Vortec4800** [comment]
Okay, I was able to modify the SDK to spit out the actual decoding error and found the problem. Since yesterday, the nearby stations in Dallas have been unavailable. This changes the darksky-unavailable key in the JSON, and so it can't decode it. In the Struct, the decoder is expecting a Bool value for that key, but it's giving a string instead. Here is the JSON snippet for the `flags` key in my full API response for reference:

	"flags": {
		"sources": ["nwspa", "cmc", "gfs", "hrrr", "icon", "isd", "madis", "nam", "sref", "darksky", "nearest-precip"],
		"nearest-station": 0.42,
		"units": "us",
		"darksky-unavailable": "Dark Sky covers the given location, but all stations are currently unavailable."
	}

**Comment by Vortec4800** [comment]
I tried running a request for a different location that has working radar stations, and that key is just missing if everything is okay, so I propose we just change the field to a String from a Bool. I'll send in a PR with this change for review.

**Comment by sxg** [comment]
Thanks for catching the error and the pull request! It does appear as if that property would be better represented as a `String?`, so I've accepted the pull request. I'll put out the official update in just a minute.
