### ISSUE TITLE
Future 7 days weather forecast 

### ISSUE THREAD

**Issue by qadir-genetech** [sxg/ForecastIO#8]
How to get weather of 7 up-coming days using your Wrapper library?

As docs says
The Forecast API lets you query for most locations on the globe, and returns:

Current conditions
Minute-by-minute forecasts out to 1 hour (where available)
Hour-by-hour forecasts out to 48 hours
Day-by-day forecasts out to 7 days

**Comment by sxg** [comment]
Use one of the two main API calls to get a `Forecast`. The weather for the upcoming 7 days will be on the `daily` property of the `Forecast` you receive. [Here are the docs for that property](http://cocoadocs.org/docsets/ForecastIO/1.5.0/Structs/Forecast.html#/s:vV10ForecastIO8Forecast5dailyGSqVS_9DataBlock_). For example:

``` swift
forecastIOClient.getForecast(latitude: myLat, longitude: myLon) { (currentForecast, error) -> Void in
  if let currentForecast = currentForecast {
    //  We got the current forecast!
    //  Print the weather for the upcoming 7 days
    print(currentForecast.daily)
  } else if let error = error {
    //  Uh-oh we have an error!
  }
}
```

Note that the `daily` property is an optional, and if Forecast.io doesn't have this data, then that property will be `nil`.

**Comment by qadir-genetech** [comment]
Very nice. Thanks for your support :+1:
